# action.yml
name: 'Snakemake GKE Action'
description: 'Run Snakemake on GKE on the respository'
inputs:
  sa_key:  # id of input
    description: 'security key'
    required: true
    default: 'World'

outputs:
  time: # id of output
    description: 'INFORMATIONAL ECHO'
runs:
  using: 'docker'
  image: 'Dockerfile'
  args:
    - ${{ inputs.sa_key }}
