# action.yml
name: 'Snakemake GKE Action'
description: 'Run Snakemake on GKE on the respository'
inputs:
  who-to-greet:  # id of input
    description: 'Who to greet'
    required: true
    default: 'World'

outputs:
  time: # id of output
    description: 'GCP EMAIL ECHO'
runs:
  using: 'docker'
  image: 'Dockerfile'
  args:
    - ${{ inputs.who-to-greet }}
    - ${{ GCP_SA_EMAIL }}
