# config file for citeseq snakemake pipeline

# directory
DATA:
    "/pbmc_test/data"

# results directory
RESULTS:
    "/pbmc_test/results"

GEX_INDEX:
    "/ref/cr2020A_star"

FEATURE_INDEX:
    "/ref/Features_20221123_star"

WHITELIST_V3:
    "/ref/3M-february-2018.txt"

WHITELIST_V2:
    "/ref/737K-august-2016.txt"

# TSV relating all sequenced libraries to sane capture names
FASTQS:
    "example_fastqs.tsv"
    
# TSV with per-capture metadata and sample ID
CAPTURES:
    "example_captures.tsv"

GEX:
    - pbmc

ADT:
    - pbmc
