name: CITE-Seq Snakemake GKE Pipeline

on: [workflow_dispatch]

jobs:
  hello_world_job:
    runs-on: ubuntu-latest
    name: A job to say hello
    steps:
      # To use this repository's private action,
      # you must check out the repository
      - name: Checkout
        uses: actions/checkout@v3
      - name: Snakemake GKE Custom Action
        uses: ./ # Uses an action in the root directory
        id: snakemake_gke_action_step
        with:
          sa_test_key: "iodfj084lkjLHK30slkj"
          sa_key: ${{ secrets.CITESEQ_SA_KEY }}
      # Use the output from the `snakemake_gke_action_step` step
      - name: Get the output time
        run: echo "The time was ${{ steps.snakemake_gke_action_step.outputs.time }}"
